# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

IntegrateDataC <- function(integration_matrix, weights, expression_cells2) {
    .Call('_FastIntegration_IntegrateDataC', PACKAGE = 'FastIntegration', integration_matrix, weights, expression_cells2)
}

